name: Update stats

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@V1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          USERNAME: Corfucinas
          SHOW_LINES_OF_CODE: true
          HEAD_FLAG: true
          SHOW_OS: true
          SHOW_PROJECTS: true
          SHOW_COMMIT: true
          SHOW_LANGUAGE: true
          SHOW_EDITORS : true
